name = "my-cloudflare-worker"
main = "src/index.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "KV_STUDENTS", id = "cc7047e7553b4f668b230f6c8d197594", preview_id = "3b8e08a706fe45469fde34b64beb2e0c" }
]

[observability]
enabled = true

[vars]
STRIPE_SECRET_KEY = "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"
STRIPE_WEBHOOK_SECRET = "whsec_l3RSHhad9Mbyqkz6Uqzty0zF7tLxvWpf"
 